server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rank?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  session:
    hostName: 127.0.0.1
    port: 6379
    password:
    maxIdle: 200
    maxTotal: 1024
    index: 0
    maxWaitMillis: 1000
    testOnBorrow: false

mybatis:
  mapperLocations: classpath:mappers/**/*.xml
  typeAliasesPackage: com.fei.rank.application.entity